version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/cli"
    schedule:
      interval: "weekly"
