repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ""
    hooks:
      - id: prettier
        args: ['--write']
        files: '\.jsx?$'
  - repo: local
    hooks:
      - id: check-header
        name: Check for license header
        entry: .precommit/check_header.sh
        language: system
        files: '\.py$'  # Adjust file pattern as needed
        exclude: '^$'
      - id: check-cli-readme
        name: Check if the CLI Readme needs an update
        entry: .precommit/check_cli_readme.sh
        language: system
