[tool.poetry]
name = "team-aide"
version = "0.1.0"
description = ""
authors = ["Team-aide incubation <team-aide@thoughtworks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
Authlib = "^1.3.0"
boto3 = "^1.34.82"
chromadb = "^0.4.24"
faiss-cpu = "^1.8.0"
fastapi = "0.109.1"
google-cloud-aiplatform = "1.44.0"
gradio = "4.19.2"
itsdangerous = "^2.1.2"
Jinja2 = "3.1.3"
langchain = "0.1.11"
langchain-google-genai = "^1.0.1"
langchain-google-vertexai = "^0.1.2"
loguru = "^0.7.2"
ollama = "^0.1.8"
openai = "^1.17.0"
pyarrow = "^15.0.2"
pypdf = "^4.2.0"
pytest = "^8.1.1"
pytest-mock = "^3.14.0"
python-frontmatter = "^1.1.0"
shapely = "^2.0.3"
tiktoken = "^0.6.0"
typing-extensions = "^4.11.0"
typing-inspect = "^0.9.0"
unstructured = "^0.13.2"
uvicorn = "^0.29.0"
langchain-openai = "^0.1.2"
python-dotenv = "^1.0.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
