name: Semgrep OSS scan

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main"]
  schedule:
    - cron: '20 17 * * *' # Sets Semgrep to scan every day at 17:20 UTC.

permissions:
  security-events: write

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      
      - name: Run full Semgrep scan
        run: semgrep scan --metrics=off --config "p/default" --sarif > semgrep.sarif

      - name: Check for high severity issues
        run: semgrep scan --metrics=off --config "p/default" --error --severity=HIGH
        continue-on-error: false

      - name: Upload SARIF file
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep.sarif
          retention-days: 7

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep